rails-i18n/config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :feedbacks
    root 'static_pages#index'
  end
end

rails-i18n/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails-i18n/app/models/feedback.rb
class Feedback < ApplicationRecord
  validates :author, presence: true
  validates :message, presence: true, length: { minimum: 5 }
end

rails-i18n/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  include Internationalization
end

rails-i18n/app/controllers/concerns/internationalization.rb
module Internationalization
  extend ActiveSupport::Concern

  included do
    around_action :switch_locale

    private

    def switch_locale(&action)
      locale = locale_from_url || locale_from_headers || I18n.default_locale
      response.set_header 'Content-Language', locale
      I18n.with_locale(locale, &action)
    end

    def locale_from_url
      locale = params[:locale]
      return locale if I18n.available_locales.map(&:to_s).include?(locale)
    end

    def locale_from_headers
      header = request.env['HTTP_ACCEPT_LANGUAGE']
      return if header.nil?

      locales = parse_header(header)
      return if locales.empty?

      detect_from_available(locales)
    end

    def parse_header(header)
      header.gsub(/\s+/, '').split(',').map do |tag|
        locale, quality = tag.split(/;q=/i)
        quality = quality ? quality.to_f : 1.0
        [locale, quality]
      end.reject { |(locale, quality)| locale == '*' || quality.zero? }
         .sort_by { |(_, quality)| quality }
         .map(&:first)
    end

    def detect_from_available(locales)
      locales.reverse.find { |l| I18n.available_locales.any? { |al| match?(al, l) } }
    end

    def match?(str1, str2)
      str1.to_s.casecmp(str2.to_s).zero?
    end

    def default_url_options
      { locale: I18n.locale }
    end
  end
end

rails-i18n/app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[ show edit update destroy ]

  # GET /feedbacks or /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1 or /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
    @feedbacks = Feedback.order(created_at: :desc)
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks or /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.save
      redirect_to new_feedback_path
    else
      @feedbacks = Feedback.order(created_at: :desc)
      render :new, status: :unprocessable_entity
    end
  end


  # PATCH/PUT /feedbacks/1 or /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: "Feedback was successfully updated." }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1 or /feedbacks/1.json
  def destroy
    @feedback.destroy!

    respond_to do |format|
      format.html { redirect_to feedbacks_path, status: :see_other, notice: "Feedback was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.expect(feedback: [ :author, :message ])
    end
end

rails-i18n/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

rails-i18n/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-i18n/app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

rails-i18n/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rails-i18n/app/views/feedbacks/_feedback.html.erb
<%= tag.article id: dom_id(feedback) do %>
  <em>
    <%= tag.time l(feedback.created_at, format: :long), datetime: feedback.created_at %><br>
    <%= t 'feedbacks.posted_by', author: feedback.author %>
  </em>
  <p>
    <%= feedback.message %>
  </p>
  <hr>
<% end %>

rails-i18n/app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback) do |form| %>
  <% if feedback.errors.any? %>
    <div style="color: red">
      <h2><%= t 'global.forms.messages.errors', count: feedback.errors.count %></h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_field :message %>
  </div>

  <div>
    <%= form.submit t('global.forms.submit') %>
  </div>
<% end %>

rails-i18n/app/views/feedbacks/edit.html.erb
<% content_for :title, "Editing feedback" %>

<h1>Editing feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Show this feedback", @feedback %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>
</div>

rails-i18n/app/views/feedbacks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Feedbacks" %>

<h1>Feedbacks</h1>

<div id="feedbacks">
  <% @feedbacks.each do |feedback| %>
    <%= render feedback %>
    <p>
      <%= link_to "Show this feedback", feedback %>
    </p>
  <% end %>
</div>

<%= link_to "New feedback", new_feedback_path %>

rails-i18n/app/views/feedbacks/new.html.erb
<% content_for :title, "New feedback" %>

<h1>New feedback</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Back to feedbacks", feedbacks_path %>
</div>

<%= render @feedbacks %>

rails-i18n/app/views/feedbacks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @feedback %>

<div>
  <%= link_to "Edit this feedback", edit_feedback_path(@feedback) %> |
  <%= link_to "Back to feedbacks", feedbacks_path %>

  <%= button_to "Destroy this feedback", @feedback, method: :delete %>
</div>

rails-i18n/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <title><%= content_for(:title) || "Lokalise I18n" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
    <ul>
      <li><%= link_to t('global.menu.home'), root_path %></li>
      <li><%= link_to t('global.menu.feedback'), new_feedback_path %></li>
    </ul>

    <ul>
      <% I18n.available_locales.each do |locale| %>
        <li>
          <% if I18n.locale == locale %>
            <%= t(locale, scope: 'locales') %>
          <% else %>
            <%= link_to t(locale, scope: 'locales'), url_for(locale: locale) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </nav>
  <%= yield %>
  </body>
</html>